from . import program
from . import plan
from . import degree
from . import courses
from . import semester
from . import batch
from . import students
from . import grades
from . import grade_sheet
from . import models